$.configApi = $.extend($.configApi, {
    "logout": "userInfo/logout",
    "chkUserStatus": "userInfo/chkUserStatus",
    "userguide": "user/get/guide/",
    "marketInfo": "/app/marketInfo/getMarketInfo/",
    "productshopgoodsdetail": "/goods/get/",
    "cart-addCarItem": "cart/addCarItem",
    "longyan-commentList": "review/common/list",
    "longyan-orderAdd": "review/common/add",
    "longyan-uploadMany": "review/common/uploadMany",
    "longyan-suggestAdd": "suggest/add",
    "longyan-suggestAddPic": "review/common/upload",
    "longyan-praise": "review/common/praise",
    "longyan-likedCount": "review/common/likedCount",
    "longyan-share": "review/common/share",
    "longyan-getAppConfig": "common/getAppConfig",
    "longguo-shopdetailinfo": "app/shopInfo/getShopDetailInfo",
    "longguo-picShopdetail": "goods/get",
    "longguo-brandinfo": "brand/get/",
    "longguo-brandGoods": "goods/get/product",
    "longguo-byBrandIdAndCityId": "app/shopInfo/get/byBrandIdAndCityId",
    "longguo-getCitysByBrandId": "app/shopInfo/getCitysByBrandId",
    "longguo-brandDeatil": "brand/get",
    "longguo-goodsGet": "goods/get",
    "longguo-getCartGoods": "goods/get/byProductIdColorAndStandard",
    "longguo-getMarketInfo": "app/marketInfo/getMarketInfo",
    "longguo-getOmsBuildingFloor": "buildingFloor/getOmsBuildingFloor",
    "longguo-getMarketPhoto": "buildingFloor/getMarketPhoto",
    "longguo-getShopList": "buildingFloor/getShopInfo",
    "longguo-getOmsBrandInfoByFloorIdAndCateId": "buildingFloor/getOmsBrandInfoByFloorIdAndCateId",
    "longguo-getShowCategory": "app/showCategory/getShowCategory",
    "longguo-getPhotoAlbumDetailByAlbumId": "photoAlbum/getPhotoAlbumDetailByAlbumId",
    "longguo-getPhotoAlbumByShopId": "photoAlbum/getPhotoAlbumByShopId",
    "longguo-checkOrder": "app/inventoryGoods/check",
    "longguo-addOrder": "app/inventoryGoods/addGoodsWithAction",
    "longguo-cancelOrder": "app/inventoryGoods/delGoodsBySku",
    "longguo-getPhotoAlbumDetail": "photoAlbum/getPhotoAlbumDetail",
    "longguo-addGuideNotebook": "app/inventoryGuide/addGuide",
    "longguo-getProductShopGoodsList": "goods/getProductShopGoodsList",
    "longguo-maininfobase": "user/get/maininfobase",
    "longguo-mainBookingData": "user/get/mainBookingData",
    "longguo-getRoomListByUserAndStatus": "user/get/getRoomListByUserAndStatus",
    "decoration-brandDeatil": "case/detail",
    "decoration-designerDetail": "designer/detail",
    "decoration-designerList": "designer/list",
    "decoration-commentsLabels": "comments/labels/booking_guid",
    "decoration-commentsLabelD": "comments/labels/designerLabel",
    "decoration-answerDetail": "knowledge/answerDetail",
    "decoration-designer": "designer/info",
    "decoration-designer-open": "designer/getDesignerDetail",
    "decoration-recuit": "activityUser/add/",
    "cms-homeDetail": "cms-web/article/home/detail",
    "cms-atlasDetail": "cms-web/atlas/detail",
    "cms-customDetail": "cms-web/article/custom/detail",
    "cms-picInfo": "cms-web/atlas/detail",
    "cms-market": "cms-web/page/market",
    "cms-discovery": "cms-web/page/discovery",
    "cms-cateoryTypeProduct": "cms-web/page/search/condition/cateoryTypeProduct",
    "cms-encyclopediaDetail": "cms-web/encyclopedia/detail",
    "cms-ad": "cms-web/ad/list",
    "cms-marketArticleDetail": "cms-web/marketArticle/detail",
    "cms-brandList": "cms-web/page/index",
    "cms-categoryTypeMarket": "cms-web/page/cmsClass/categoryTypeMarket",
    "user-getUserAttentionCount": "userAttention/getItemAttentionCount",
    "user-IsItemUserAttention": "userAttention/IsItemUserAttention",
    "user-addUserAttention": "userAttention/addUserAttention",
    "user-cancelUserAttention": "userAttention/cancelUserAttention",
    "user-IsItemCollectioned": "userCollection/IsItemCollectioned",
    "user-addUserCollection": "userCollection/addUserCollection",
    "user-cancelUserCollection": "userCollection/cancelUserCollection",
    "user-login": "user/authenticate",
    "user-registration": "user/registration",
    "user-resetPassword": "user/updatePassword",
    "user-captcha": "common/captcha",
    "user-smsCode": "common/smsCode",
    "user-homeForApp": "user/homeForApp",
    "im-saleAssistan": "imShop/getSalesAssistantList",
    "im-getImAccountImId": "imAccount/getImId",
    "im-getSalesAssistant": "imShop/getSalesAssistant",
    "coupon-refer": "type",
    "longguo-marketNumberRefer": "app/marketInfo/getMarketInfo",
    "longguo-salesclerk": "user/get/maininfobase",
    "longguo-showCategory": "app/showCategory/get",
    "longguo-showCategoryfilterShopper": "app/showCategory/filterShopper",
    "longguo-byShowCategory": "brand/get/byShowCategory",
    "coupon-getCoupons": "channel",
    "coupon-subPromotion":"subPromotion/sku",
    "sh-getPublishContentByOpenId": "sales/getPublishContentByOpenId",
    "ilvb-liveData": "room/get/more/list",
    "ilvb-livehall": "room/get/HallRoomlist",
    "ilvb-room": "room/viewer/in/",
    "sms-messageStatus": "message/wap/status",
    "sms-messageList": "message/list",
    "search-query": "query",
    "searchcore-query": "",
    "ilvb-roofBrief": "room/get/roomBrief",
    "ilvb-room-get-more-list": "/room-get-more-list",
    "cms-campaign-index":"cms-web/campaign/index" ,
    "cms-campaign-market-coupon" :"cms-web/campaign/market/coupon" ,
    "cms-campaign-market-product":"cms-web/campaign/market/product",
    //XML
    "cms1-campaign-index": "/campaign/index",
    "cms1-campaign-market-coupon": "/campaign/market/coupon",
    "cms1-campaign-market-product": "/campaign/market/product",
    //
    "coupon-couponList": "storeIds",
    "coupon-channel": "channel/1/name/App/subChannel/1/user/cupon",
    "house-queryHotHouseList": "house/queryHotHouseList",
    "house-queryNewHouseList": "house/queryNewHouseList",
    "house-queryBestHouseList": "house/queryBestHouseList",
    "house-sendMessage": "house/sendMessage",
    "house": "house/",
    "im-imConsultant-getConsultant": "imConsultant/getConsultant",
    "coupon-couponListData": "user/cupon",
    "crm-myBooking": "c/myBooking/list",
    "crm-designerBooking": "c/designerBooking/detail",
    "crm-commentsLabelD": "c/comments/labels/booking_guid",
    "crm-guidBooking-detail": "c/guidBooking/detail",
    "crm-guidBooking": "c/guidBooking/add",
    "crm-guidBooking-delete": "c/guidBooking/cancel",
    "order-queryOrder": "p-trade-oc-web/orderApi/cApp/queryOrder",
    "order-orderInfo": "p-trade-oc-web/orderApi/golable/orderInfo",
    "order-count": "p-trade-oc-web/orderApi/cApp/queryOrder/alarm/count",
    "coupon-active": "promotion/list/info",
    // 快速注册登录
    "user-shortcutSignin":"user/shortcutSignin",
    //获取会员收货信息
    "user-addrInfo":"userAddress/findUserAddressByUserId",
    //情人节活动
    "valentine-luckydraw":"content",
    "valentine-prize":"luckyDraw",
    "valentine-getPrize":"receivePrize",
    //汶水1号：闻鸡起舞 大牌上新
    "wenshui-active": "promotion/list/info",
    //两天来了活动
    "cmsAc-prizeList":"prizeList",
    "cmsAc-getPrize":"addPrize",
    "cmsAc-shareCount":"shareCount",
    "cmsAc-addShare":"addShare",
    //五一活动接口
    "wenshui-prizeRecord": "list/prizeRecord",
    "wenshui-prizeList": "prizeList",
    "wenshui-timeNow": "time/now",
    "wenshui-rushPurchase":"rushPurchase",
    "wenshui-up-prizeRecord":"update/prizeRecord"
});

